force-app/main/default/objects/Assigned_Training__c/Assigned_Training__c.object-meta.xml
<CustomObject>
    <description>added from sfdx plugin</description>
    <label>Learning Module</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assigned_Training__c/fields/Complete__c.field-meta.xml
<CustomField>
    <fullName>Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Learning_Topic__c/Learning_Topic__c.object-meta.xml
<CustomObject>
    <label>Learning Topic</label>
    <nameField>
        <label>Learning Topics Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Learning Topics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Learning_Topic__c/fields/Learning_Module__c.field-meta.xml
<CustomField>
    <fullName>Learning_Module__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Learning Module</label>
    <referenceTo>Assigned_Training__c</referenceTo>
    <relationshipLabel>Learning Topics</relationshipLabel>
    <relationshipName>Learning_Topics</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/learningController.cls
public with sharing class learningController {

    @AuraEnabled(cacheable=true)
    public static Learning_Topic__c getRelatedLearningTopic(String recordId) {
        Learning_Topic__c topic = [SELECT Id FROM Learning_Topic__c WHERE Learning_Module__c = :recordId LIMIT 1];
        return topic;
    }

    @AuraEnabled(cacheable=false)
    public static Assigned_Training__c getLearningModule(String recordId) {
        Assigned_Training__c module = [SELECT Id, Complete__c FROM Assigned_Training__c WHERE Id = :recordId LIMIT 1];
        return module;
    }

    @AuraEnabled(cacheable=true)
    public static Assigned_Training__c getParentLearningModule(String recordId) {
        Learning_Topic__c topic = [SELECT Id, Learning_Module__c FROM Learning_Topic__c WHERE Id = :recordId LIMIT 1];
        Assigned_Training__c module = [SELECT Id FROM Assigned_Training__c WHERE Id = :topic.Learning_Module__c LIMIT 1];
        return module;
    }    

    @AuraEnabled(cacheable=false)
    public static void updateLearningModule(String recordId, Boolean complete) {
        Assigned_Training__c module = [SELECT Id, Complete__c FROM Assigned_Training__c WHERE Id = :recordId LIMIT 1];
        module.Complete__c = complete;
        update module;
    }

}