force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <label>Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Zip or Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State or Province</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Employee records for Onboarding Demo</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Applicant_Record__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Record</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Finance/Accounting</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>Technology &amp; Products</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Hotel Operations</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>Zip or Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CSG - CFL</fullName>
            </value>
            <value>
                <fullName>CSG - Services</fullName>
            </value>
            <value>
                <fullName>Account Executive</fullName>
            </value>
            <value>
                <fullName>Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Manager</fullName>
            </value>
            <value>
                <fullName>Solution Engineer</fullName>
            </value>
            <value>
                <fullName>Alliances &amp; Channels</fullName>
            </value>
            <value>
                <fullName>Market Readiness</fullName>
            </value>
            <value>
                <fullName>Sales Strategy</fullName>
            </value>
            <value>
                <fullName>Products - Other</fullName>
            </value>
            <value>
                <fullName>Products - Product Manager</fullName>
            </value>
            <value>
                <fullName>Products - Program Manager</fullName>
            </value>
            <value>
                <fullName>Products - User Experience</fullName>
            </value>
            <value>
                <fullName>Products - Content Experience</fullName>
            </value>
            <value>
                <fullName>Technology - Developer</fullName>
            </value>
            <value>
                <fullName>Technology - Quality Engineer</fullName>
            </value>
            <value>
                <fullName>Technology - Other</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Hotel Operations Manager</fullName>
                <label>Manager</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Send_Notification__c.field-meta.xml
<CustomField>
    <fullName>Send_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State or Province</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Hire</fullName>
            </value>
            <value>
                <fullName>Setup</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Onboarded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/User_Record__c.field-meta.xml
<CustomField>
    <fullName>User_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Record</label>
    <referenceTo>User</referenceTo>
    <relationshipName>EmployeesRecords</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Equipment__c/Equipment__c.object-meta.xml
<CustomObject>
    <description>Items which can be provisioned to a user. (User Onboarding Demo)</description>
    <label>Equipment</label>
    <nameField>
        <displayFormat>EQ-{00000000}</displayFormat>
        <label>Equipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Equipment</relationshipLabel>
    <relationshipName>Equipment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/sampleDataCreation.cls
public with sharing class sampleDataCreation {

    public static void createData() { 

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];

        User u = new User(
            Alias= 'mperez',
            Email= 'perez@example.com',
            EmailEncodingKey= 'ISO-8859-1',
            LanguageLocaleKey= 'en_US',
            LastName= 'Perez',
            LocaleSidKey= 'en_US',
            TimeZoneSidKey= 'America/Los_Angeles',
            Username= 'mperez@example.com',
            ProfileId= p.Id
        );
 
        insert u;

        Applicant__c apl = 
            new Applicant__c(
                City__c= 'Las Vegas',
                Email__c= 'perez@example.com',
                First_Name__c= 'Maria',
                Last_Name__c= 'Perez',
                Name= 'Maria Perez',
                Phone__c= '(555) 583-4832',
                PostalCode__c= '89109',
                State__c= 'NV',
                Street_Address__c= '3570 S Las Vegas Blvd'
            );
 
        insert apl;

        Employee__c emp = 
            new Employee__c(
                Applicant_Record__c=apl.Id, 
                City__c='Las Vegas',
                Department__c='Hotel Operations',
                Email__c='perez@example.com', 
                First_Name__c='Maria',
                Last_Name__c='Perez',
                Name= 'Maria Perez',
                Phone__c= '(555) 583-4832',
                PostalCode__c= '89109',
                Role__c= 'Hotel Operations Manager',
                Send_Notification__c= true,
                // Start_Date__c= '2020-02-12',
                State__c='NV',
                Status__c= 'New Hire',
                Street_Address__c= '3570 S Las Vegas Blvd',
                User_Record__c = u.Id
            );

        insert emp;
    
        Equipment__c equip = new Equipment__c(
            Employee__c = emp.Id
        );

        insert equip;
    }
}